version: '3.4'

services:
    snmp_mock:
        image: darkman66/snmp-mock:0.1
        ports:
          - "161:161/udp"
        environment:
          - SNMP_PORT=161
          - SNMP_COMMUNITY="public"
          - BASE_OID="1.3.6"
          - APP_PORT=8087
        volumes:
          - type: volume
            source: sample_oids
            target: /app/oids
            volume:
              nocopy: true

volumes:
  sample_oids:
